#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_file binary /usr/bin/upload_digest_lists
for file in $(find /etc/ima/digest_lists -type f); do
    copy_file binary $file
done

mkdir ${DESTDIR}/sys
